### ISSUE TITLE
Passthrough is stopped before flushing output

### ISSUE THREAD

**Issue by jonlundy** [vektah/gorunpkg#4]
When a command completes it stops execution before writing standard out is complete.

Minimal repeatable code:
```
package main

import "fmt"

func main() {
    for i:=0; i<5000; i++ {
        fmt.Println("TEXT TEXT TEXT TEXT TEXT", i)
        fmt.Println("TEXT TEXT TEXT TEXT TEXT", i)
        fmt.Println("TEXT TEXT TEXT TEXT TEXT", i)
        fmt.Println("TEXT TEXT TEXT TEXT TEXT", i)
    }
    fmt.Println("DONE")
}
```
This should output up to 4999 but on repeated runs will randomly end at different values.

**Comment by vektah** [comment]
I can take a look over the weekend, unless you want to take a stab at a pr?

**Comment by jonlundy** [comment]
I think it is because you defer the closing stderr/stdout till after os.Exit() is called and it doesn't return. ill give a stab at it.

**Comment by jonlundy** [comment]
PR #5 fixes.
